### ISSUE TITLE
这个软件好像只适用于835芯片的小米手机，请问小米MIX2S该如何操作。

### ISSUE THREAD

**Issue by wangchuanyes** [moonheart/sagit-logo-gen#1]
我用这个软件制作了845芯片的小米MIX2S的开机第一屏，刷进去有错误。
是不是我需要提取MIX2S官方logo.img里的图片，再用你这个软件制作就可以呢？

**Comment by moonheart** [comment]
把`genlogo.py`里的 offset 和 magic 替换成MIX2S的应该就可以了。

具体的数值可以通过`binwalk`和 HexEditor 查看原版logo.img

**Comment by wangchuanyes** [comment]
虽然我操作不了，但还是感谢你的回复。
[MIX2S_logo.zip](https://github.com/moonheart/sagit-logo-gen/files/2299957/MIX2S_logo.zip)

**Comment by moonheart** [comment]
请测试这个为MIX2S生成的第一屏，如果可用，我会把源代码推送到仓库。
[logo_new_mix2s.zip](https://github.com/moonheart/sagit-logo-gen/files/2300129/logo_new_mix2s.zip)

**Comment by wangchuanyes** [comment]
测试成功，开机第一屏你加入了“test”字样，多谢。

**Comment by moonheart** [comment]
我推送到了 `MIX2S` 分支中，请使用该分支的程序生成你的开机第一屏文件。
