### ISSUE TITLE
bmp可以是其他分辨率吗?

### ISSUE THREAD

**Issue by eebssk1** [moonheart/sagit-logo-gen#3]
02.bmp 558x992分辨率感觉小了点,于是调成1080x1920,,,结果发现一半花屏了,不知道是不是偏移的问题,不知道maintainer有没有想法改进啥的?.....

**Comment by eebssk1** [comment]
找到问题了。。。图片直接的空隙太小了，改偏移量的话可能要动引导器。。。

**Comment by eebssk1** [comment]
在abl和xbl里找不到便宜地址，也没看见相关加载代码，，难道直接写在pbl里了？

**Comment by moonheart** [comment]
@eebssk1 读取的偏移量是固定的，我也不知道在哪里可以改![image](https://user-images.githubusercontent.com/15916990/54110994-c288db00-441d-11e9-8aa9-2a581045062d.png)

**Comment by eebssk1** [comment]
@moonheart 两个加载器里都找不到相关信息，感觉硬编码在pbl了😂
惹不起 惹不起 🌚🌝

**Comment by moonheart** [comment]
@eebssk1 写在pbl的话就没办法了😂

**Comment by eebssk1** [comment]
GG😇
