### ISSUE TITLE
New format

### ISSUE THREAD

**Issue by ghost** [moonheart/sagit-logo-gen#4]
Is there a new format? I'm unable to apply the correct splash images with latest Q based firmware. The fastboot logo isn't applied correctly.

Have the offsets been changed?

**Comment by moonheart** [comment]
What's your phone model? Offsets may various between diffrent models and Android versions, you may find out latest offset with some steps. See [wiki](https://github.com/moonheart/sagit-logo-gen/wiki).

**Comment by ghost** [comment]
Disregard, I figured it out successfully.
